language: generic
services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: never

env:
  global:
    - NOT_TEST_BUILD=true
    - BEFORE_INIT="apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654"

matrix:
  include:
    - env: ROS_DISTRO=noetic
  allow_failures:
    - env: ROS_DISTRO=kinetic DOCKER_IMAGE=rosindustrial/noether:kinetic

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
